# Generated by Django 4.0.1 on 2022-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars'), ('GBP', 'Pounds')], max_length=3),
        ),
    ]
