# Generated by Django 4.0.1 on 2022-01-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_userdata_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pounds'), ('USD', 'Dollars'), ('EUR', 'Euros')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website_link_1',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website_link_2',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website_link_3',
            field=models.URLField(null=True),
        ),
    ]
