# Generated by Django 4.0.1 on 2022-01-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_userdata_id_alter_userdata_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['username']},
        ),
    ]
