# Generated by Django 4.0.1 on 2022-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_userdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pounds'), ('USD', 'Dollars')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website_link_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website_link_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website_link_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
