# Generated by Django 4.0.1 on 2022-01-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_userdata_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pounds'), ('USD', 'Dollars'), ('EUR', 'Euros')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
